"""add name and last_name entries to the users table

Revision ID: 137042aa318b
Revises: 18746f7b2f79
Create Date: 2025-06-24 22:04:25.425789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '137042aa318b'
down_revision = '18746f7b2f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
